### ISSUE TITLE
Using with Negroni?

### ISSUE THREAD

**Issue by ZedCode** [TV4/graceful#2]
Hi,

I'm currently playing with a bunch of ways to implement a graceful shutdown for people who are not primarily Go developers and this looks like a really great library to do that with! I'm having a bit of an issue making it not exit immediately though:

```go
// from my server package, in my server.go file
func NewServer(logger service.Logger) *negroni.Negroni {
	n := negroni.New()
	n.Use(negroni.NewRecovery())
	n.Use(servicelogger.NewLogger(logger))
	mx := mux.NewRouter()
	initRoutes(mx, formatter)
	n.UseHandler(mx)
	return n
}
```
When the application starts, I'm using a service library, so I just do the following:
```go
func (p *program) run() {
	graceful.ListenAndServe(&http.Server{Addr: ":8999", Handler: apiserver.NewServer(logger)})
}
```
When I build this code it exits immediately. Do I need to implement my own `ServeHTTP` and have my `apiserver.NewServer` return something that implements `ServeHTTP` to make this work as expected?

Thanks!
ZC

**Comment by peterhellberg** [comment]
The handler (A `*negroni.Negroni` in your case) would need to implement the [Shutdowner](https://github.com/TV4/graceful/blob/ebdc053ac500f16c73c60f124c279055c996a466/graceful.go#L78-L80) interface in order to do any cleanup after `graceful` has closed all connections to the `*http.Server`.

This is an example of running `graceful` and `negroni`:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/TV4/graceful"
	"github.com/urfave/negroni"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		time.Sleep(15 * time.Second)

		fmt.Fprintf(w, "Hello from a very slow handler!")
	})

	n := negroni.Classic()

	n.UseHandler(mux)

	hs := &http.Server{Addr: ":3000", Handler: n}

	graceful.LogListenAndServe(hs, log.New(os.Stdout, "", 0))
}
```

You can test this by running `go run graceful-negroni.go` in one terminal and `curl http://0.0.0.0:3000` in a separate terminal. Then press Ctrl-C in the first terminal.

This should result in the following output:

```
Listening on http://0.0.0.0:3000
^C
Server shutdown with timeout: 15s
[negroni] 2017-11-08T19:49:53+01:00 | 200 | 	 15.00157019s | 0.0.0.0:3000 | GET /
Finished all in-flight HTTP requests
Shutdown finished 2s before deadline
```

**Comment by peterhellberg** [comment]
The handler (A `*negroni.Negroni` in your case) would need to implement the [Shutdowner](https://github.com/TV4/graceful/blob/ebdc053ac500f16c73c60f124c279055c996a466/graceful.go#L78-L80) interface in order to do any cleanup after `graceful` has closed all connections to the `*http.Server`.

This is an example of running `graceful` and `negroni`:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/TV4/graceful"
	"github.com/urfave/negroni"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		time.Sleep(15 * time.Second)

		fmt.Fprintf(w, "Hello from a very slow handler!")
	})

	n := negroni.Classic()

	n.UseHandler(mux)

	hs := &http.Server{Addr: ":3000", Handler: n}

	graceful.LogListenAndServe(hs, log.New(os.Stdout, "", 0))
}
```

You can test this by running `go run graceful-negroni.go` in one terminal and `curl http://0.0.0.0:3000` in a separate terminal. Then press Ctrl-C in the first terminal.

This should result in the following output:

```
Listening on http://0.0.0.0:3000
^C
Server shutdown with timeout: 15s
[negroni] 2017-11-08T19:49:53+01:00 | 200 | 	 15.00157019s | 0.0.0.0:3000 | GET /
Finished all in-flight HTTP requests
Shutdown finished 2s before deadline
```

**Comment by peterhellberg** [comment]
The handler (A `*negroni.Negroni` in your case) would need to implement the [Shutdowner](https://github.com/TV4/graceful/blob/ebdc053ac500f16c73c60f124c279055c996a466/graceful.go#L78-L80) interface in order to do any cleanup after `graceful` has closed all connections to the `*http.Server`.

This is an example of running `graceful` and `negroni`:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/TV4/graceful"
	"github.com/urfave/negroni"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		time.Sleep(15 * time.Second)

		fmt.Fprintf(w, "Hello from a very slow handler!")
	})

	n := negroni.Classic()

	n.UseHandler(mux)

	hs := &http.Server{Addr: ":3000", Handler: n}

	graceful.LogListenAndServe(hs, log.New(os.Stdout, "", 0))
}
```

You can test this by running `go run graceful-negroni.go` in one terminal and `curl http://0.0.0.0:3000` in a separate terminal. Then press Ctrl-C in the first terminal.

This should result in the following output:

```
Listening on http://0.0.0.0:3000
^C
Server shutdown with timeout: 15s
[negroni] 2017-11-08T19:49:53+01:00 | 200 | 	 15.00157019s | 0.0.0.0:3000 | GET /
Finished all in-flight HTTP requests
Shutdown finished 2s before deadline
```

**Comment by peterhellberg** [comment]
@ZedCode Feel free to comment on this issue if you need any further clarification.

**Comment by ZedCode** [comment]
Nope, this is perfect and made me realize that the problematic part of my code is integration with github.com/kardianos/service -- This code: `func (p *program) run()` is invoked as `go p.run()`, so it's exiting immediately. I'm not exactly sure how I'm going to overcome this yet, but it certainly has nothing to do with this graceful library :)
